# Generated by Django 5.0.7 on 2024-08-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100, unique=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('related_words', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
