# Generated by Django 5.0.7 on 2024-07-30 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('machine_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('redis_key', models.CharField(blank=True, editable=False, max_length=400)),
            ],
        ),
    ]
